const ACTION_TYPES = {
    GET_PRODUCT_ASYNC: 'GET_PRODUCT_ASYNC',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',
    ADD_PRODUCT_ASYNC: 'ADD_PRODUCT_ASYNC',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',

    LOAD_IMAGES:'LOAD_IMAGES',
    LOAD_IMAGES_SUCCESS:'LOAD_IMAGES_SUCCESS',
    LOAD_IMAGES_FAILD:'LOAD_IMAGES_SUCCESS',

    START_LOADING:'START_LOADING',
    STOP_LOADING:'STOP_LOADING',
}

export { ACTION_TYPES };